config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  get 'home/index'

  devise_for :users 
  resources :contracts
  
 resources :items do
      resources :ratings, except: [:show, :index]
  end 
  
  resources :rentals do
    put :change_to_accept
    get :acceptance_msg
  end
  resources :items 
  resources :categories
  resources :users
  resources :locations
  resources :user_types
  get "/fetch_items" => 'items#from_category', as: 'fetch_items'
  post "/from_search" => 'items#from_search', as: 'from_search' # search in all items
  get "/all_items" => 'items#all_items', as: 'all_items'
  post "/" => "items#search" , as: "search_items" #search in home page
  get "/unathorized_access" => 'shared#unathorized_access', as: 'unathorized_access'
  root 'home#index'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :recipient, class_name: "User"
  belongs_to :actor, class_name: "User"
  belongs_to :notifiable, polymorphic: true

  scope :unread, ->{ where(read_at: nil) }
  scope :recent, ->{ order(created_at: :desc).limit(5) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def index
    @notifications = Notification.where(recipient: current_user).recent
  end

  def mark_as_read
    @notifications = Notification.where(recipient: current_user).unread
    @notifications.update_all(read_at: Time.zone.now)
    render json: {success: true}
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:recipient_id, :actor_id, :read_at, :action, :notifiable_id, :notifiable_type)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipient_id %><br>
    <%= f.number_field :recipient_id %>
  </div>
  <div class="field">
    <%= f.label :actor_id %><br>
    <%= f.number_field :actor_id %>
  </div>
  <div class="field">
    <%= f.label :read_at %><br>
    <%= f.datetime_select :read_at %>
  </div>
  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :notifiable_id %><br>
    <%= f.number_field :notifiable_id %>
  </div>
  <div class="field">
    <%= f.label :notifiable_type %><br>
    <%= f.text_field :notifiable_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Recipient</th>
      <th>Actor</th>
      <th>Read at</th>
      <th>Action</th>
      <th>Notifiable</th>
      <th>Notifiable type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.recipient_id %></td>
        <td><%= notification.actor_id %></td>
        <td><%= notification.read_at %></td>
        <td><%= notification.action %></td>
        <td><%= notification.notifiable_id %></td>
        <td><%= notification.notifiable_type %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipient:</strong>
  <%= @notification.recipient_id %>
</p>

<p>
  <strong>Actor:</strong>
  <%= @notification.actor_id %>
</p>

<p>
  <strong>Read at:</strong>
  <%= @notification.read_at %>
</p>

<p>
  <strong>Action:</strong>
  <%= @notification.action %>
</p>

<p>
  <strong>Notifiable:</strong>
  <%= @notification.notifiable_id %>
</p>

<p>
  <strong>Notifiable type:</strong>
  <%= @notification.notifiable_type %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>