config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  get 'home/index'

  devise_for :users 
  resources :contracts
  
 resources :items do
      resources :ratings, except: [:show, :index]
  end 
  
  resources :rentals do
    put :change_to_accept
    get :acceptance_msg
  end
  resources :items 
  resources :categories
  resources :users
  resources :locations
  resources :user_types
  get "/fetch_items" => 'items#from_category', as: 'fetch_items'
  post "/from_search" => 'items#from_search', as: 'from_search' # search in all items
  get "/all_items" => 'items#all_items', as: 'all_items'
  post "/" => "items#search" , as: "search_items" #search in home page
  get "/unathorized_access" => 'shared#unathorized_access', as: 'unathorized_access'
  root 'home#index'

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  

   def avg_rating
        rating = Rating.where(item_id: self.id)
        sum = 0
         rating.each  do |r| 
           sum = sum + r.stars

        #   if r.blank?
        #     @avg_rating= 0
        #   else
        #     @avg_rating = r.average(:stars).round(2)
          end 
           
           if rating.count==0
             avg=0
          else
            avg = sum/rating.count
          end
           
   end 
  
end 

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]
  before_action :set_item
 # before_action :authenticate_user!

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
 
  end


  # GET /ratings/new
  def new
    @rating = Rating.new
    @item = Item.find(params[:item_id])
    @rating.item = Item.find(params[:item_id])
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)
    @rating.user_id = current_user.id
    @item = Item.find(params[:item_id])
    @rating.item = Item.find(params[:item_id])
    if @rating.save
      redirect_to @rating.item
    else 
      render 'new'

    end 
end 
  #   respond_to do |format|
  #     if @rating.save
  #       format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
  #       format.json { render :show, status: :created, location: @rating }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @rating.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end




  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_item
            @item = Item.find(params[:item_id])
    end 


    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:stars, :comment, :user_id, :item_id)
    end

end 

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<div class="container-fluid text-left row">    
	  <div class="row content">
	
	    <div class="col-sm-3 sidenav">
      </div>
      
      <div class="col-sm-6"> 
      <h1>New Rating</h1>
      <div id= "myform" class="container">
        <%= form_for([@item, @rating]) do |f| %>
          <% if @rating.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>
        
              <ul>
              <% @rating.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
        
          <div class="field">
            <%= f.label :stars %>    (5 is Best)<br>
            <%= f.select :stars, [1,2,3,4,5], :id => "fieldsize1"%>  
          </div>
        
        
        <div class="field">
            <div id="star-rating"></div>
          </div>
        
             <%= f.hidden_field :item_id %>
        
          <br>
          <div class="field">
            <%= f.label :comment %><br>
            <%= f.text_area :comment,:id => "fieldsize"%>
          </div>
          
          <br>
          <div class="actions">
          
         <%= f.submit "Submit my Rating",:id => "itemShowButt2" %>
         <%= link_to 'Back',item_path(@item),:id => "newItemBack" %>

          </div>
        <% end %>
        
        
        
        <script>
          $('#star-rating').raty({
            path: '/images/',
            scoreName: 'rating[stars]'
          });
        </script>
        <br>
        </div>
        
        <div class="col-sm-3 sidenav">
        </div>
    
    </div>
</div>        
        
         
        
        
          
        
        

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>


<%= link_to 'Show', @rating %> |
<%= link_to 'Back',item_path(@item) %>

app/views/ratings/new.html.erb
<%= render 'form' %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Stars:</strong>
  <%= @rating.stars %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @rating.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @rating.user.name %>
</p>

<p>
  <strong>Item:</strong>
  <%= @rating.item %>
</p>


  <!--Code for showing stars and rating-->
  

           <% if @ratings.blank? %>
              <h3>No reviews just yet, would you like to add the first!</h3>
              <%= link_to "Write Review", new_item_rating_path(@item), class: "btn btn-danger" %>
           <% else %>
              <% @ratings.each do |rating| %>

                   <%= rating.user.name %>

                  <% (1..rating.stars).each do |i| %>   
                  <%= image_tag "golden_star.png", :class => "style_image" %>  
                  <%end%>
                  
                  <p><%= rating.comment %></p>
            </div>
            
            <% end %>
         <% end %>
  
    <!--Code for showing stars and rating-->
<%= link_to "Rate itttt" , new_item_rating_path(@item) %>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>