config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  get 'home/index'

  devise_for :users 
  resources :contracts
  
 resources :items do
      resources :ratings, except: [:show, :index]
  end 
  
  resources :rentals do
    put :change_to_accept
    get :acceptance_msg
  end
  resources :items 
  resources :categories
  resources :users
  resources :locations
  resources :user_types
  get "/fetch_items" => 'items#from_category', as: 'fetch_items'
  post "/from_search" => 'items#from_search', as: 'from_search' # search in all items
  get "/all_items" => 'items#all_items', as: 'all_items'
  post "/" => "items#search" , as: "search_items" #search in home page
  get "/unathorized_access" => 'shared#unathorized_access', as: 'unathorized_access'
  root 'home#index'

end

app/models/rental.rb
class Rental < ActiveRecord::Base
  after_create :set_to_pending
  belongs_to :user 
  belongs_to :item 
  has_one :contract
  has_many :notifications , through: :user
  
  scope :pending,        -> { where(status: 'pending') }
  scope :current,        -> { where(status: 'accepted').where("end_date>= ?", Date.today).where("start_date<= ?", Date.today) }
  scope :past,        -> { where(status: 'accepted').where("end_date<= ?", Date.today)}
  
  def days
    (end_date - start_date).to_i
  end
  
  
  private
  def set_to_pending
    self.update_attribute(:status, "pending")
  end
  
  
  end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  skip_authorize_resource :only => :acceptance_msg
  # GET /rentals 
  # GET /rentals.json
  def index
    @rentals = current_user.Rental_request
  end
def change_to_accept
    @rental = Rental.find params[:rental_id]
    @rental.update_column(:status, "accepted") 
    Notification.create(recipient: @rental.user, actor: current_user, action: "accepted", notifiable: @rental)
    Transaction.create(item_name: @rental.item.name, borrower: @rental.user, lender: @rental.item.user,  item: @rental.item, rental: @rental, start_date: @rental.start_date, end_date: @rental.end_date)
    redirect_to rental_acceptance_msg_path
  end
  # GET /rentals/1
  # GET /rentals/1.json
  def show
    @rentals = current_user.Rental_request
  end

# GET /rentals/1
  # GET /rentals/1.json
  def acceptance_msg
  end

  # GET /rentals/new
  def new
    if user_signed_in?
    @rental = current_user.rentals.build
     @rental.item = Item.find(params[:item_id])
     @ratings = Rating.where(item_id: params[:item_id])
   else
     redirect_to user_session_url
   end
  end

  # GET /rentals/1/edit
  def edit
    authorize! :update , @rental

  end

  # POST /rentals
  # POST /rentals.json
  def create
    @rental = Rental.new(rental_params)
    respond_to do |format|
      if @rental.save
        format.html { redirect_to @rental, notice: 'Rental was successfully created.' }
        format.json { render :show, status: :created, location: @rental }
        # Create the notifications
        Notification.create(recipient: @rental.item.user, actor: current_user, action: "requested", notifiable: @rental)
      
      else
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1
  # PATCH/PUT /rentals/1.json
  def update
    authorize! :update , @rental
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    authorize! :destroy , @rental
    if @rental.user != current_user
      Notification.create(recipient: @rental.user, actor: current_user, action: "declined", notifiable: @rental.item)
      @rental.destroy
      respond_to do |format|
        format.html { redirect_to rentals_url }
        format.json { head :no_content }
      end
  else
    notification = Notification.where(notifiable: @rental)
    notification[0].destroy
    @rental.destroy
    redirect_to @rental.item
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_params
      params.require(:rental).permit(:item_id, :user_id, :start_date, :end_date , :quantity, :comment)
    end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/_all_requests.html.erb
<table class="table">
        <thead>
          <tr>
            <th>User</th>
            <th>Item</th>
            <th>Start date</th>
            <th>End date</th>
            <th>Days requested</th>
            <th colspan="2"></th>
          </tr>
        </thead>
        <tbody>
          <% @rentals.each do |rentals| %>
          <tr>
            <td><%= rentals.user.name %></td>
            <td><%= rentals.item.name %></td>
            <td><%= rentals.start_date %></td>
            <td><%= rentals.end_date %></td>
            <td><%= rentals.days %></td>
            <td> <%= link_to('Accept', rental_change_to_accept_path(:rental_id =>rentals.id), :method => :put, :confirm => "Sure?", class:'btn btn-success') %></td>
            <td><%= link_to 'Decline', rentals, method: :delete , class:'btn btn-danger' %></td>
          </tr>
          <% end %>
        </tbody>
</table>

app/views/rentals/_form.html.erb
<div class="row content">
  
  <div class="col-sm-1 sidenav"></div>
  
  <div class="col-sm-10 text-center">
    
    <div id="myform" class="container"> 
    
    <br><h1><b><%= @rental.item.name %></b></h1>
    <hr id="homehr2">
    <br>
    
    
    <div class="container-fluid text-left">
      
      <div class="col-sm-6">
          
        <div class="itemShowAccount itemShowExample"></div>
        
        <br><br>
      
        <div class="row">
          <div id="itemShowButt">Description:</div>
        </div>
        
        <div class="row">
          <div id="itemShowButt1"><%= @rental.item.description %></div>
        </div>
      
        <br>
        
        <div class="row">
          <div class="col-sm-4" id="itemShowButt">Daily Price:</div> 
          <div class="col-sm-8" id="itemShowButt1"><%= @rental.item.daily_price %> QAR</div>
        </div>
        
        <div class="row">  
          <div class="col-sm-4" id="itemShowButt">Weekly Price:</div>
          <div class="col-sm-8" id="itemShowButt1"><%= @rental.item.weekly_price %> QAR</div>
        </div>
        
        <div class="row">  
          <div class="col-sm-4" id="itemShowButt">Monthly Price:</div>
          <div class="col-sm-8" id="itemShowButt1"><%= @rental.item.monthly_price %> QAR</div>
        </div>
        
        <div class="row">  
          <div class="col-sm-4" id="itemShowButt">Available Quantity:</div>
          <div class="col-sm-8" id="itemShowButt1"><%= @rental.item.quantity_left %></div>
        </div>
         
        <div class="row"> 
          <div class="col-sm-4" id="itemShowButt">Category:</div>
          <div class="col-sm-8" id="itemShowButt1"><%= @rental.item.category.name %></div>
        </div>
        
        <div class="row">
          <div class="col-sm-4" id="itemShowButt">Item Dimensions:</div>
          <div class="col-sm-8" id="itemShowButt1"><%= @rental.item.size %></div>
        </div>
        
        <div class="row">
          <div class="col-sm-4" id="itemShowButt">Item Weight:</div>
          <div class="col-sm-8" id="itemShowButt1"><%= @rental.item.weight %></div>
        </div>
        
      </div>
 
      
    <div class="text-left col-sm-6">
      
      <div class="row content">
          
        <%= form_for(@rental) do |f| %>
        <% if @rental.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@rental.errors.count, "error") %> prohibited this rental from being saved:</h2>
      
            <ul>
            <% @rental.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      
      
        <%= f.hidden_field :user_id %>
        <%= f.hidden_field :item_id %>
        <%= f.hidden_field :status%>
      
        <div id= "rentalform" class="container">  
        
          <h2 class="text-center">Borrow Item</h2>
          
          <hr id="homehr2">
          
          <div id="myfield" class="field">
            <%= f.label :start_date %> 
            <%= f.date_select :start_date %>
          </div>
          
          <div id="myfield"class="field">
            <%= f.label :end_date %> 
            <%= f.date_select :end_date %>
          </div>
          
          <div id="myfield"class="field">
            <%= f.label :quantity %>
            <%= f.select(:quantity, 1.upto(@rental.item.quantity_left).to_a) %>
          </div>
          
          <div id= "mybutton" class="actions"> <br />
            <%= f.submit "Submit Request",:id => "itemShowButt2"%><br><br>
          </div>
          
        </div>
        
        <% end %>
              
      </div>
      
      <br><br>
      
      <div id="itemShowButt4">
           
           
           <% if @ratings.blank? %>
              <h3>Would you like to Rate Item?
              <%= link_to "Write Review", new_item_rating_path(@rental.item_id), class: "btn btn-danger" %></h3><br>
              
           <% else %>
            
            <h3>Ratings:</h3><br>
              <% @ratings.each do |rating| %>
              
                  <%= rating.user.name %>
                  (<% (1..rating.stars).each do |i| %>   
                  <%= image_tag "golden_star.png", :class => "style_image" %>  
                  <%end%>)
                  
                  <p><%= rating.comment %></p>
                  <hr>
            <% end %>
            
            
            <% end %>
            
            
            
            
          </div> 
      
    </div>

  </div>
      
  <br><br>
  
  
  <%= link_to 'Back', items_path, class:'btn btn-default', id:'itemShowButt2' %>
  
  <br><br>
  
</div>

<div class="col-sm-1 sidenav"></div>

</div>

app/views/rentals/acceptance_msg.html.erb
<div class="container-fluid text-left row">    
    <div class="row content">
	    
	  <div class="col-sm-2 sidenav">
      </div>
      
      <div class="col-sm-8"> 
        
        <div id="thanks" class="jumbotron text-xs-center">
          <h1 class="display-3">Thank You!</h1>
          <p>
            <strong>
                You will be receiving a confirmation as soon as we process your order.
            </strong>
            Delivery service will contact you shortly for delivery.
          </p>
            
        
        </div>
                
      </div>
      
      <div class="col-sm-2 sidenav">
      </div>
    
    </div>
</div>


<!--https://codepen.io/JacobLett/pen/vyegPV-->

app/views/rentals/index.html.erb
<div class="container-fluid text-center">    
  <div class="row content items">
    
    <div class="col-sm-2 sidenav"></div>

    <div class="col-sm-8">
      
      <div class="container-fluid">
        <!--<!%= link_to 'New Rental', new_rental_path, class:'btn btn-default' %>-->
        <h1 id="renthead">Rental requests</h1>
        <p id="renthead">You have the following requests</p>            
        <%= render 'all_requests' %>
      </div>
      
    </div>
    
    
    <div class="col-sm-2 sidenav">
    </div>

  </div>
</div>

app/views/rentals/new.html.erb
<div class="container-fluid text-left row">    

    <div id= mylink>
        <%= render 'form' %>
    </div>
    
    
            

</div>
      

app/views/rentals/show.html.erb
<div class="container-fluid text-center">    
  <div class="row content">
    
    
    
    <div class="col-sm-2 sidenav"></div>
    
    
    
    <div class="col-sm-8 text-left">
      <h1 class="display-3">Your Rental Request Summary</h1>
      <p>
        <strong>Start date:</strong>
        <%= @rental.start_date %>
      </p>
      
      <p>
        <strong>End date:</strong>
        <%= @rental.end_date %>
      </p>
      
      <p>
        <strong>Item:</strong>
        <%= @rental.item.name %>
      </p>
      
      <br>
      <%= link_to 'Cancel Request', @rental, method: :delete , class:'btn btn-danger' %>
      <br><br>

    </div>
    
    
    
    <div class="col-sm-2 sidenav"></div>
    
    
    
  </div>
</div>