config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  get 'home/index'

  devise_for :users 
  resources :contracts
  
 resources :items do
      resources :ratings, except: [:show, :index]
  end 
  
  resources :rentals do
    put :change_to_accept
    get :acceptance_msg
  end
  resources :items 
  resources :categories
  resources :users
  resources :locations
  resources :user_types
  get "/fetch_items" => 'items#from_category', as: 'fetch_items'
  post "/from_search" => 'items#from_search', as: 'from_search' # search in all items
  get "/all_items" => 'items#all_items', as: 'all_items'
  post "/" => "items#search" , as: "search_items" #search in home page
  get "/unathorized_access" => 'shared#unathorized_access', as: 'unathorized_access'
  root 'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user 
  belongs_to :category
  has_many :rentals ,  dependent: :destroy
  
  
  def avg_rating
        rating = Rating.where(item_id: self.id)
        sum = 0
         rating.each  do |r| 
           sum = sum + r.stars

        #   if r.blank?
        #     @avg_rating= 0
        #   else
        #     @avg_rating = r.average(:stars).round(2)
          end 
           
           if rating.count==0
             avg=0
          else
            avg = sum/rating.count
          end
           
   end
  
  
  ##validations 
  
  validates :name, presence: true
  validates :description, presence: true
  validates :quantity, presence: true
  validates :size, presence: true
  validates :weight, presence: true, numericality: { :greater_than_or_equal_to => 0 }
  validates :daily_price, presence: true, numericality: { :greater_than_or_equal_to => 0 }
  validates :weekly_price, presence: true, numericality: { :greater_than_or_equal_to => 0 }
  validates :monthly_price, presence: true, numericality: { :greater_than_or_equal_to => 0 }

 ##############################################################
 
  def quantity_left
    q = self.quantity
    Rental.where(item_id: self.id).current.each do |r|
      q = q - r.quantity
      puts r.id
    end
    return q
  end
  def owner
    return User.find(self.user_id)
  end
  #functions
  def prices
    price = Pricing.find(self.id)
    "#{price.daily}/per day, #{price.monthly}/per month, #{price.yearly}/per year"
  end
  
  
  
  
end 

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , except: [:index]
  load_and_authorize_resource 
  skip_authorize_resource :only => [:from_category , :index]
  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    @categories = Category.all

  end

def from_category
    @selected = Item.where(:category_id => params[:category_id])
    respond_to do |format|
        format.js
    end
end
def all_items
    @items = Item.all
    @categories = Category.all
    respond_to do |format|
        format.js
    end
end
def from_search
  @q = "%#{params[:query]}%"
  @items = Item.where("name LIKE ? or description LIKE ?", @q, @q)
  respond_to do |format|
        format.js
    end
end


  #def authorize
   # if current_user.nil?
    #  redirect_to root_path , alert: "Needs to Login"
    #else
     # if @item && @item.user != current_user
      #  redirect_to root_path, alert: "Not authorized only #{@item.user} has access to this item"
      #end
    #end
#end



  # GET /items/1
  # GET /items/1.json
  def show
    @rentals= Rental.where(:category_id => params[:category_id])
    @ratings = Rating.where(:item_id => params[:id])
    
   
  end

  # GET /items/new
  # GET /items/new
  def new
    @item = current_user.items.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
     @item = current_user.items.build(item_params)


    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :size, :weight, :quantity, :daily_price, :weekly_price, :monthly_price, :user_id, :category_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group col-sm-6">
      <%= f.label " " %> <b>Item Name*</b>
      <div>
      <%= f.text_field :name, class:'form-control' %>
      </div>
      </div>
      
   <div class="form-group col-sm-6">
      <%= f.label " " %> <b>Item Description/Specifications*</b>
      <div>
      <%= f.text_area:description, class:'form-control', placeholder:"Suggestions: Condition of item, How old is it? Model type (if relevant), Color,  Durability, etc." %>
      </div>
    </div>
    
    
  <div class="form-group col-sm-6">
    <%= f.label " " %> <b>Item Size*</b>
    <div>
    <%= f.text_field :size, class:'form-control', placeholder:"Suggestions: Dimensions in cm, Refernece to another standarrd sized object." %>
  </div>
  </div>
  
    <div class="form-group col-sm-6">
    <%= f.label :daily_price %>* (QAR)
    <div>
    <%= f.text_field :daily_price, class:'form-control' %>
  </div>
  </div> 
  
    <div class="form-group col-sm-6">
    <%= f.label " " %> <b>Item Weight*</b> (Kg)
    <div>
    <%= f.text_field :weight, class:'form-control' %>
  </div>
  </div> 
 
    <div class="form-group col-sm-6">
    <%= f.label :weekly_price %>* (QAR)
    <div>
    <%= f.text_field :weekly_price, class:'form-control' %>
  </div>
  </div>
  
  <div class="form-group col-sm-6">
    <%= f.label :quantity %>*
    <div>
    <%= f.text_field :quantity, class:'form-control' %>
  </div>
  </div> 



  <div class="form-group col-sm-6">
    <%= f.label :monthly_price %>* (QAR)
    <div>
    <%= f.text_field :monthly_price, class:'form-control' %>
  </div>
  </div> 


    <div class="form-group col-sm-6 dropdown">
      <%= f.label :category_id %>*
      <div>
        <%= f.collection_select  :category_id, Category.all,  :id , :name, :prompt => "Select category" %>
      </div>
    </div>
  
    <div class="actions form-group">
      <%= f.submit id:'itemShowButt2' %>
      <%= link_to 'Cancel', items_path, class:'btn btn-default', id:"newItemBack" %>
      <br><br><br><br><br><br><br>
    </div>
    
<% end %>

app/views/items/_item_grid.html.erb
<div id="items_grid">
<%= render partial: 'items_list', locals: {items: items}  %>
</div>

app/views/items/_items_list.html.erb
<div class="container-fluid text-center">    

    <div class="col-sm-1 sidenav"></div>
    
    <div class="col-sm-10 text-center"> 

      <div id="items_div">
        
        <% if items.count == 0%>
          <br>
          <h3 id="itemsheader">Sorry, There are no Items to View!</h3><br>
          <%= link_to 'Add Item', new_item_path, class:'btn btn-default', id:'itemShowButt2' %>
          <br><br><br><br><br>
        <% end %>
    
        <% if user_signed_in? %>
        
          <% items.each do |item| %>
          
          
          <div class="panel-group">
            <div class="panel panel-default" id="itemspanel">
              <div class="panel-heading"><b><%= item.name %> (<%= item.weekly_price %> QR/ Week)</b></div>
              <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
              <div id="paneldiv"><b>Description:</b> <%= item.description.first(20) %></div><br>
              <div id="paneldiv"><b>Posted by:</b> <%= item.user.name %></div><br>
              <%if  item.quantity_left==0 %>
              <div id="paneldiv"><b>Current quantity:</b> Out of stock</div><br>
              <% else %>
              <div id="paneldiv"><b>Current quantity:</b> <%= item.quantity_left %></div><br>
              <% end %>
              <% if can? :destroy , item %>
              <div class="text-center"><%= link_to 'View Item', item, class:'btn btn-default' %> | <%= link_to 'Remove', item, method: :delete , class:'btn btn-danger' %></div>
             
             
             
              <% else %>
              
                <% if current_user.pending_request(item.id).count == 0 %>
                
                  <div class="text-center"><%= link_to 'Borrow',  new_rental_path(:item_id => item.id), class:'btn btn-default', disabled: item.quantity_left==0  %>
                <% else %>
                  <div class="text-center"><%= link_to 'Requested',  current_user.pending_request(item.id)[0], class:'btn btn-default' %>
                <% end %>
                
                
                
              
              <% x= item.avg_rating  %>
        
              <% if x > 0 %>
              <%= link_to "Rate Item", new_item_rating_path(item.id), class:'btn btn-default' %> </div><br>
              Average Rating: <%= item.avg_rating  %>

              <% (1..x).each do |i| %>
              <%= image_tag "golden_star.png", :class => "style_image" %>  

              <% end %>
              
              <% else %>
              <br>
              <%= link_to "No Ratings yet, Rate Item", new_item_rating_path(item.id), class:'btn btn-default' %> </div><br>

              
             <% end %>
                          <% end %>


            </div>
          </div>
            
            
          
          <% end %>
          
        <% else %>

          <% items.each do |item| %>
          
          
          <div class="panel-group">
            <div class="panel" id="itemspanel">
              <div class="panel-heading"><b><%= item.name %> (<%= item.weekly_price %> QR/ Week)</b></div>
              <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
              <div id="paneldiv"><b>Description:</b> <%= item.description.first(20) %></div><br>
              <div id="paneldiv"><b>Posted by:</b> <%= item.user.name %></div><br>
              <div id="paneldiv"><b>Current quantity:</b> <%= item.quantity_left %></div><br>
              



              <div class="text-center"><%= link_to 'View Item', item, class:'btn btn-default' %></div>
              

            </div>
          </div>
          
            <% if items.count == 0%>
              <h3 id="itemsheader">Sorry there are no items to view!</h3>
            <% end %>
            
          <% end %>
        
        <% end %>
        
      </div>
    
    </div>
    
    <div class="col-sm-1 sidenav"></div>
    
</div>

app/views/items/_sidebar_menu.html.erb
<br><h1 id="itemsheader">Available Equipment</h1><br>

<div class="container-fluid text-center">    

  <div class="col-sm-1"></div>
  
  <div class="col-sm-10 text-center"> 
      
    <b id="filterText">To Filter:</b>&nbsp;  
    <%= link_to 'All Items', all_items_url, :remote => true, class:'btn btn-default btn-change', id:"categorySideBar" %>
    <% @categories.each do |category| %>
      | <%= link_to category.name, fetch_items_path(:category_id => category.id), :remote => true, class:'btn btn-default btn-change', id:"categorySideBar" %>
    <% end %>
    <br><br>
    
    <%= form_tag from_search_path  , :remote => true do %>
      <div class="input-group stylish-input-group">
      <input type="text" class="form-control" name ="query" type ="text" placeholder="Search an Item (e.g: Mini Fridge, Camera, Tent, etc)" >
        <span class="input-group-addon">
          <button type="submit">
              <span class="glyphicon glyphicon-search"></span>
          </button>  
        </span>
      </div>
    <% end %>
    
  </div>
  
  <div class="col-sm-1"></div>

</div>

app/views/items/all_items.js.erb
$("#items_grid").html("<%= escape_javascript(render partial: 'items_list', locals: { items: @items} ) %>"); 

app/views/items/edit.html.erb
<div class="container-fluid text-center">    
  <div class="row content">
    
    
    
    <div class="col-sm-3 sidenav"></div>
    
    
    
    <div class="col-sm-6 text-left">

    <h1>Editing Item</h1>

    <%= render 'form' %>

    </div>
    
    
    
    <div class="col-sm-3 sidenav"></div>
    
    
    
  </div>
</div>

app/views/items/from_category.js.erb
$("#items_grid").html("<%= escape_javascript(render partial: 'items_list', locals: { items: @selected } ) %>"); 

app/views/items/from_search.js.erb
$("#items_grid").html("<%= escape_javascript(render partial: 'items_list', locals: { items: @items} ) %>"); 

app/views/items/index.html.erb
<%= render 'sidebar_menu' %>
<%= render partial: 'item_grid', locals: { items: @items} %>

app/views/items/new.html.erb
<div class="container-fluid text-center">    
  <div class="row content">
    
    
    
    <div class="col-sm-2 sidenav"></div>
    
    
    
    <div class="col-sm-8 text-left"> 
    
    <br><h1 class="text-center">Add A New Item</h1><br>

    <%= render 'form' %>

    </div>
    
    
    
    <div class="col-sm-2 sidenav"></div>
    
    
    
  </div>
</div>

app/views/items/show.html.erb
<div class="container-fluid text-center">    

    <div class="col-sm-1 sidenav"></div>
    
    <div class="col-sm-10 text-center">
      
      <div id="myform" class="container"> 
      
      <br><h1><b><%= @item.name %></b></h1>
      <hr id="homehr2">
      <br>
      
      
      <div class="container-fluid text-left">
        
   
        
        <div class="col-sm-6">
          
          <div class="itemShowAccount itemShowExample"></div>
          
          <br><br>
          
          <div id="itemShowButt3">  
          <% if @ratings.blank? %>
            <h3>No reviews just yet, would you like to add the first?</h3>
            <%= link_to "Write Review", new_item_rating_path(@item), class: "btn btn-danger" %><br><br>
          <% else %>
          
            <h3>Ratings:</h3><br>
            
              <% @ratings.each do |rating| %>
            
                  <%= rating.user.name %>
                  
                  (<% (1..rating.stars).each do |i| %>   
                  <%= image_tag "golden_star.png", :class => "style_image" %> 
                  <%end%>)
                  
                  <p><%= rating.comment %></p><hr>
            <% end %>
            <% end %>
          </div>
          
          <br><br>
          
        </div>
        
        
        <div class="text-left col-sm-6">
          
          <div class="row">
            <div class="col-sm-4" id="itemShowButt">Description:</div><br>
            <div class="col-sm-8" id="itemShowButt1"><%= @item.description %></div>
          </div>
        
          <br>
          
          <div class="row">
            <div class="col-sm-4" id="itemShowButt">Posted By:</div> 
            <div class="col-sm-8" id="itemShowButt1"><%= @item.user.name %></div>
          </div>
          
          <div class="row">
            <div class="col-sm-4" id="itemShowButt">Daily Price:</div> 
            <div class="col-sm-8" id="itemShowButt1"><%= @item.daily_price %> QAR</div>
          </div>
          
          <div class="row">
            <div class="col-sm-4" id="itemShowButt">Weekly Price:</div>
            <div class="col-sm-8" id="itemShowButt1"><%= @item.weekly_price %> QAR</div>
          </div>
          
          <div class="row">
            <div class="col-sm-4" id="itemShowButt">Monthly Price:</div>
            <div class="col-sm-8" id="itemShowButt1"><%= @item.monthly_price %> QAR</div>
          </div>
          
          <div class="row">  
            <div class="col-sm-4" id="itemShowButt">Available Quantity:</div>
            <div class="col-sm-8" id="itemShowButt1"><%= @item.quantity_left %></div>
          </div>
           
          <div class="row"> 
            <div class="col-sm-4" id="itemShowButt">Category:</div>
            <div class="col-sm-8" id="itemShowButt1"><%= @item.category.name %></div>
          </div>
          
          <div class="row">
            <div class="col-sm-4" id="itemShowButt">Item Dimensions:</div>
            <div class="col-sm-8" id="itemShowButt1"><%= @item.size %></div>
          </div>
          
          <div class="row">
            <div class="col-sm-4" id="itemShowButt">Item Weight:</div>
            <div class="col-sm-8" id="itemShowButt1"><%= @item.weight %></div>
          </div>
          
        </div>

      </div>
      </div>
     
      <br><br>
      
      <%= link_to 'Edit', edit_item_path(@item), class:'btn btn-default', id:'itemShowButt2' %> |
      <%= link_to 'Back', items_path, class:'btn btn-default', id:'itemShowButt2' %>
   
    <br><br>
    
    </div>

    <div class="col-sm-1 sidenav"></div>

</div>